version: '3'

services:
  app:
    build: ./docker/app
    command: >
      sh -c "
          rm -f tmp/pids/server.pid &&
          dockerize -wait tcp://mysql:3306 -timeout 60s &&
          bundle install &&
          bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    volumes:
      - .:/griffin
    ports:
      - '3000:3000'
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql/
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: griffin
      MYSQL_USER: griffin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
